# Generated by Django 6.0 on 2025-12-28 12:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upvote_count', models.PositiveIntegerField(default=0, verbose_name='upvote count')),
                ('raw_content', models.TextField(verbose_name='raw_content')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is deleted')),
            ],
            options={
                'verbose_name': 'Reply',
                'verbose_name_plural': 'Replies',
                'ordering': ['thread', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='reason')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RESOLVED', 'Resolved')], default='PENDING', max_length=8, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('color', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code', regex='^#[A-Fa-f0-9]{6}$')], verbose_name='color')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upvote_count', models.PositiveIntegerField(default=0, verbose_name='upvote count')),
                ('raw_content', models.TextField(verbose_name='raw_content')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is deleted')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('is_locked', models.BooleanField(default=False, verbose_name='is locked')),
                ('reply_count', models.PositiveIntegerField(default=0, verbose_name='reply_count')),
            ],
            options={
                'verbose_name': 'Thread',
                'verbose_name_plural': 'Threads',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Trigram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(db_index=True, max_length=3, unique=True, verbose_name='value')),
            ],
            options={
                'verbose_name': 'Trigram',
                'verbose_name_plural': 'Trigrams',
            },
        ),
    ]
