# Generated by Django 6.0 on 2025-12-22 20:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('color', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code', regex='^#[A-Fa-f0-9]{6}$')], verbose_name='color')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upvote_count', models.PositiveIntegerField(db_index=True, default=0, verbose_name='upvote count')),
                ('raw_content', models.TextField(verbose_name='raw content')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='is deleted')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('upvotes', models.ManyToManyField(blank=True, related_name='upvoted_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='upvotes')),
            ],
            options={
                'verbose_name': 'Reply',
                'verbose_name_plural': 'Replies',
                'ordering': ['thread', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upvote_count', models.PositiveIntegerField(db_index=True, default=0, verbose_name='upvote count')),
                ('raw_content', models.TextField(verbose_name='raw content')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='is deleted')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='title')),
                ('is_locked', models.BooleanField(db_index=True, default=False, verbose_name='is locked')),
                ('reply_count', models.PositiveIntegerField(default=0, verbose_name='reply_count')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='threads.category', verbose_name='category')),
                ('tagged_courses', models.ManyToManyField(blank=True, related_name='tagged', to='courses.course', verbose_name='tagged courses')),
                ('tagged_documents', models.ManyToManyField(blank=True, related_name='tagged', to='courses.resource', verbose_name='tagged documents')),
                ('tags', models.ManyToManyField(blank=True, related_name='tagged', to='threads.tag', verbose_name='tags')),
                ('upvotes', models.ManyToManyField(blank=True, related_name='upvoted_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='upvotes')),
            ],
            options={
                'verbose_name': 'Thread',
                'verbose_name_plural': 'Threads',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='reason')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RESOLVED', 'Resolved')], db_index=True, default='PENDING', max_length=8, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='threads.reply', verbose_name='reply')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='reporter')),
                ('thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='threads.thread', verbose_name='thread')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
            },
        ),
        migrations.AddField(
            model_name='reply',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='threads.thread', verbose_name='thread'),
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['category', '-created_at'], name='threads_thr_categor_8959f8_idx'),
        ),
    ]
