# Generated by Django 6.0 on 2025-12-28 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('threads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AddField(
            model_name='reply',
            name='upvotes',
            field=models.ManyToManyField(blank=True, related_name='upvoted_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='upvotes'),
        ),
        migrations.AddField(
            model_name='report',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='threads.reply', verbose_name='reply'),
        ),
        migrations.AddField(
            model_name='report',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='reporter'),
        ),
        migrations.AddField(
            model_name='thread',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AddField(
            model_name='thread',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='threads.category', verbose_name='category'),
        ),
        migrations.AddField(
            model_name='thread',
            name='tagged_courses',
            field=models.ManyToManyField(blank=True, related_name='tagged', to='courses.course', verbose_name='tagged courses'),
        ),
        migrations.AddField(
            model_name='thread',
            name='tagged_documents',
            field=models.ManyToManyField(blank=True, related_name='tagged', to='courses.resource', verbose_name='tagged documents'),
        ),
        migrations.AddField(
            model_name='thread',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tagged', to='threads.tag', verbose_name='tags'),
        ),
        migrations.AddField(
            model_name='thread',
            name='upvotes',
            field=models.ManyToManyField(blank=True, related_name='upvoted_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='upvotes'),
        ),
        migrations.AddField(
            model_name='report',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='threads.thread', verbose_name='thread'),
        ),
        migrations.AddField(
            model_name='reply',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='threads.thread', verbose_name='thread'),
        ),
        migrations.AddField(
            model_name='thread',
            name='trigrams',
            field=models.ManyToManyField(blank=True, related_name='threads', to='threads.trigram', verbose_name='trigrams'),
        ),
    ]
