# Generated by Django 6.0 on 2025-12-28 12:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=25, unique=True, validators=[django.core.validators.RegexValidator(message='Course code must be in the format "CS F111" or "MATH F101"', regex='^[A-Z]{2,4}\\s[A-Z]{1}\\d{3}$')], verbose_name='code')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.department')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('type', models.CharField(choices=[('PDF', 'PDF'), ('VIDEO', 'Video'), ('LINK', 'Link')], max_length=5, verbose_name='type')),
                ('link', models.URLField(unique=True, verbose_name='link')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='courses.course', verbose_name='course')),
            ],
            options={
                'verbose_name': 'Resource',
                'verbose_name_plural': 'Resources',
                'unique_together': {('course', 'title')},
            },
        ),
    ]
